name: Benchmark

# only one can tun at a time.
# Actions access a common cache entry and may corrupt it.
concurrency: cd-benchmark

on:
  push:
    branches:
      - master
      - benchmark

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bootstrap
        run: yarn
      # Run benchmark with custom tooling and stores the output to a file
      - name: Run performance tests
        run: yarn benchmark
        env:
          BENCHMARK_RESULTS_PATH: ./benchmark/results.json
          BENCHMARK_RESULTS_CSV_DIR: ./benchmark

      # Download previous benchmark result from cache (if exists)
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./benchmark/history.json
          key: ${{ runner.os }}-benchmark-history-tmp

      # Upload results + history (even on error so partial results can be read)
      - name: Upload full benchmark results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-data
          path: ./benchmark

      # Run `github-action-benchmark` action
      - name: Store benchmark result
        run: |
          cd .github/workflows/benchmark
          yarn
          yarn run-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BENCHMARK_RESULTS_PATH: ./benchmark/results.json
          BENCHMARK_HISTORY_PATH: ./benchmark/history.json
          THRESHOLD: 2
      # Upload the updated cache file for the next job by actions/cache
